spring:
  jpa:
    hibernate:

      ddl-auto: create-drop
    database: mysql
  datasource:
      url: jdbc:mysql://localhost:3306/security_bd
      username: root
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8090

