spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  #    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/register_bd
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8081